### ISSUE TITLE
turn-again-reporter has an undeclared dependency on ANSI

### ISSUE THREAD

**Issue by halostatue** [swifthand/turn-again-reporter#1]

**Comment by swifthand** [comment]
Thanks for the issue report!

The project only depends on the `minitest-reporters` gem, which is what depends on the `ansi` gem (and thereby also depends on `ruby-progressbar` and `minitest` itself). I am not very experienced in publishing gems, and was not aware that tracking a dependency's dependency is something to be done. 

I apologize if not doing so is bad form. Do you have a recommendation on how to proceed? Is it only second-order dependencies that I ought to specify?

**Comment by halostatue** [comment]
Hmmm. I see the problem. It’s a slightly different problem. I have `turn-again-reporter` _and_ `minitest-reporters` in my Gemfile as:

``` ruby
gem 'minitest-reporters', require: false
gem 'turn-again-reporter', require: false
```

Something in one of my environments requires `ansi` directly, so we have it. In another, we didn’t.

If you add `require 'ansi'` (I think that’s the require you need) at the top of your reporter (right under `require 'minitest/reporters'`), the error I was seeing will go away. You are right that `ansi` is a transitive dependency, and my fix was not the right fix (adding `gem 'ansi'`).
